export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCESSFULL = 'SIGN_IN_SUCESSFULL';
export const SEND_MESSAGE_TO_SERVER = 'SEND_MESSAGE_TO_SERVER';
export const SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_SYSTEM_MESSAGE = 'ADD_SYSTEM_MESSAGE';
export const MAP_CHANGED = 'MAP_CHANGED';
export const WINDOW_SIZE_SET = 'WINDOW_SIZE_SET';
