export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCESSFULL = 'SIGN_IN_SUCESSFULL';
export const SEND_MESSAGE_TO_SERVER = 'SEND_MESSAGE_TO_SERVER';
export const SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
